module.exports = {
  i18n: {
    localeDetection: false,
    locales: [
      "en-us",
      // "ar-ar",
      // "bg-bg",
      // "bs-ba",
      // "ca-es",
      // "da-dk",
      // "de-de",
      // "el-gr",
      // "en-ca",
      // "en-gb",
      "es-la",
      // "es-es",
      // "es-mx",
      // "fa-ir",
      // "fi-fi",
      // "fr-fr",
      // "fr-ca",
      // "hi-in",
      // "hr-hr",
      // "id-id",
      // "it-it",
      // "ja-jp",
      // "ko-kr",
      // "mk-mk",
      // "ms-my",
      // "pl-pl",
      // "pt-br",
      // "pt-pt",
      // "ro-ro",
      // "ru-ru",
      // "sl-si",
      // "sr-rs",
      // "th-th",
      // "vi-vn",
      // "zh-cn"
    ],
    defaultLocale: "en-us",
  },
};
