export default {
  language: 'Idioma',
  navigation: 'Navegación',
  home: 'Inicio',
  blog: 'Blog',
  projects: 'Proyectos',
  cv: 'Currículo de vida',
  logIn: 'Iniciar sesión',
  signUp: 'Registrarte',
  profile: 'Perfil',
  settings: 'Ajustes',
  logOut: 'Cerrar sesión',
  chooseYourPreferredLanguage: 'Escoja su idioma preferido',
  group: 'Grupo',
  link: 'Enlace',
  connectWithMe: 'Conectese conmigo',
  sitemap: 'Sitemap',
  contactUs: 'Contáctenos',
  termsAndConditions: 'Términos y Condiciones',
  privacyPolicy: 'Política de privacidad'
};
